[phases.setup]
nixPkgs = ["python39", "libGL"]
aptPkgs = ["libglib2.0-0", "libsm6", "libxext6", "libxrender-dev"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements-railway.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2"
